require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - vendor/**/*
    - node_modules/**/*

#################### Style ####################

Style/Documentation:
  Enabled: false

#################### Lint ####################

Lint/AmbiguousBlockAssociation:
  Exclude:
    - lib/tasks/*

#################### Metrics ####################

Metrics/AbcSize:
  Max: 30
  Exclude:
    - lib/tasks/*

Metrics/BlockLength:
  Exclude:
    - lib/tasks/*

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/tasks/*

Metrics/MethodLength:
  Max: 20
  Exclude:
    - lib/tasks/*

Metrics/PerceivedComplexity:
  Max: 15

#################### Layout ####################

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EndAlignment:
  Exclude:
  - lib/tasks/*

Layout/LineLength:
  Enabled: false
