require: rubocop-performance

AllCops:
  Exclude:
    - config.ru
    - Rakefile
    - db/**/*
    - bin/**/*
    - config/**/*
    - vendor/**/*
    - node_modules/**/*

#################### Style ####################

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

#################### Lint ####################

Lint/AmbiguousBlockAssociation:
  Exclude:
    - lib/tasks/*

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

#################### Metrics ####################

Metrics/AbcSize:
  Max: 30
  Exclude:
    - lib/tasks/*

Metrics/BlockLength:
  Exclude:
    - lib/tasks/*

Metrics/MethodLength:
  Max: 20
  Exclude:
    - lib/tasks/*

Metrics/PerceivedComplexity:
  Max: 10

#################### Layout ####################

Layout/LineLength:
  Enabled: false

Layout/EndAlignment:
  Exclude:
  - lib/tasks/*

Layout/SpaceAroundMethodCallOperator:
  Enabled: true
