x-ruby-args: &ruby-args
  BUNDLER_VERSION_ARG: $BUNDLER_VERSION
  RUBY_VERSION_ARG: $RUBY_VERSION
x-rails-environment: &rails-environment
  RAILS_ENV: development
  EDITOR: vi
  MALLOC_ARENA_MAX: 2
  WEB_CONCURRENCY: 1

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
    extra_hosts:
      host.docker.internal: host-gateway
    depends_on:
      - web
  web:
    build:
      context: .
      target: development
      dockerfile: ./docker/rails/Dockerfile
      args:
        <<: *ruby-args
    expose:
      - 3000
    volumes:
      - ./:/app:cached
      - bundle:/bundle:cached
      - bundle_cache:/app/tmp/cache:cached
      - rubocop_cache:/root/.cache/rubocop_cache:cached
    tty: true
    environment:
      <<: *rails-environment
    depends_on:
      - db
  db:
    image: postgres:14.5-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=ja_JP.UTF-8'
volumes:
  bundle:
  bundle_cache:
  rubocop_cache:
  postgres:
