version: '3.7'
services:
  web:
    container_name: web-container
    build:
      context: .
      dockerfile: ./docker/web/prd/Dockerfile
      args:
        DB_HOST: $DB_HOST
        DB_DATABASE: $DB_DATABASE
        DB_USERNAME: $DB_USERNAME
        DB_PASSWORD: $DB_PASSWORD
    ports:
      - 80:80
    env_file:
      - ./docker/env/prd.env
    tty: true
    depends_on:
      - db
  db:
    container_name: db-container
    build: ./docker/db
    volumes:
      - ./docker/db/storage:/var/lib/mysql:cached
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
