version: '3.7'
services:
  web:
    container_name: web-container
    build:
      context: .
      dockerfile: ./docker/web/prd/Dockerfile
      args:
        DB_HOST: $DB_HOST
        DB_DATABASE: $DB_DATABASE
        DB_USERNAME: $DB_USERNAME
        DB_PASSWORD: $DB_PASSWORD
    command: ash -c "rm -f tmp/pids/server.pid && RAILS_ENV=production bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    env_file:
      - ./docker/env/prd.env
    environment:
      RAILS_SERVE_STATIC_FILES: 'true'
      EDITOR: 'vi'
    tty: true
    depends_on:
      - db
  db:
    container_name: db-container
    build: ./docker/db
    volumes:
      - ./docker/db/storage:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
