version: '3.7'
services:
  web:
    container_name: web-container
    build:
      context: .
      dockerfile: ./docker/web/dev/Dockerfile
    ports:
      - 3000:3000
      - 3035:3035
    volumes:
      - ./:/novel_checker:cached
    environment:
      EDITOR: 'vi'
    tty: true
    depends_on:
      - db
  db:
    container_name: db-container
    build: ./docker/db
    volumes:
      - ./docker/db/storage:/var/lib/mysql:cached
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
