version: '3'

x-ruby-args: &ruby-args
  BUNDLER_VERSION_ARG: $BUNDLER_VERSION
  RUBY_VERSION_ARG: $RUBY_VERSION
x-rails-environment: &rails-environment
  RAILS_ENV: development
  EDITOR: vi
  MALLOC_ARENA_MAX: 2
  WEB_CONCURRENCY: 1

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/dev/Dockerfile
      args:
        <<: *ruby-args
    ports:
      - 3000:3000
      - 3035:3035
    volumes:
      - ./:/app:cached
      - bundle:/bundle:cached
      - bundle_cache:/app/tmp/cache:cached
      - rubocop_cache:/root/.cache/rubocop_cache:cached
    stdin_open: true
    tty: true
    environment:
      <<: *rails-environment
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=ja_JP.UTF-8'
volumes:
  bundle:
  bundle_cache:
  rubocop_cache:
  postgres:
