version: '3.7'
services:
  web:
    build: 
      context: .
      dockerfile: ./docker/web/dev/Dockerfile
    volumes:
      - .:/novel_checker
    ports:
      - 3000:3000
      - 3035:3035
    environment:
      RAILS_SERVE_STATIC_FILES: 'true'
    depends_on:
      - db
    tty: true
  db:
    build: ./docker/db
    volumes:
      - ./docker/db/storage:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
