default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  database: <%= Rails.application.credentials.database %>
  username: <%= Rails.application.credentials.username %>
  password: <%= Rails.application.credentials.password %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
