default: &default
  adapter: postgresql
  template: template0
  encoding: utf8
  collation: ja_JP.UTF-8
  ctype: ja_JP.UTF-8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000
  username: <%= ENV.fetch('DATABASE_USER') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  database: <%= ENV.fetch('DATABASE_NAME') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
